services:
  server:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOC_READER_URL=${DOC_READER_URL}
      - FACE_SDK_URL=${FACE_SDK_URL}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"